---
- hosts: all

  tasks:
        # tasks file for check_services
     - name: comprobamos si shorewall est치 corriendo
       shell: shorewall status | grep running
       register: resultado
       ignore_errors: true
     
     
     - name: resultado es
       debug: msg={{ resultado }}
      
     
     - name: iniciamos shorewall si est치 apagado
       shell: shorewall start
       when: resultado is failed 

     - name: comprobamos si sshd est치 corriendo
       shell: systemctl status sshd | grep running
       register: resultado
       ignore_errors: true
     
     
     - name: resultado es
       debug: msg={{ resultado }}
      
     
     - name: iniciamos sshd si est치 apagado
       shell: systemctl start sshd
       when: resultado is failed 

