---
- hosts: all

  tasks:
        # tasks file for check_services
     - name: comprobamos si shorewall está corriendo
       shell: shorewall status | grep running
       register: resultado
       ignore_errors: true
     
     
     - name: resultado es
       debug: msg={{ resultado }}
      
     
     - name: iniciamos shorewall si está apagado
       shell: shorewall start
       when: resultado is failed 
