---
- hosts: all

  tasks:
  - name: install example application
    copy: 
      src: test.sh
      dest: /tmp/
      owner: root
      group: root

  - name: ejecutamos sh
    shell: sh /tmp/test.sh
